### ISSUE TITLE
Looping player breaks progress bar

### ISSUE THREAD

**Issue by CHPraxis** [afollestad/easy-video-player#58]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Easy Video Player.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

I want a video (an mp4) to loop - restart when completed.  To accomplish this, I implemented:

`@Override
    public void onCompletion(EasyVideoPlayer player) {
            player.seekTo(0);
            player.start();
    }`

This correctly loops the video.  However, while the video restarts upon completion, the progress bar remains at the end and does not track the video's playback, nor do the timestamps, unless I pause and unpause.

**Comment by CHPraxis** [comment]
I was able to resolve the problem by changing your code to call mSeeker.setProgress(mSeeker.getMax()); before calling the callback's oncompletion instead of after.  I would suggest making this change in your build if it does not cause other problems.

When EasyVideoPlayer's onCompletion is called, it calls the callback's oncompletion, *then* sets mSeeker to max, which potentially overwrites anything the the callback did.

**Comment by afollestad** [comment]
I fixed this issue, *and* added looping configuration so you don't have to manually restart the video.

**Comment by CHPraxis** [comment]
Strangely, if I set .setLoop(true), I still encounter the original progress bar bug.

But if I manually seekTo like in my code sample above, it now works in 3.0.  Since that resolves my problem, thank you!!

**Comment by afollestad** [comment]
Very weird! I tested that and it was working on my Pixel. 

I'll look at it again later. Glad I solved your problem though!

**Comment by afollestad** [comment]
Ah, I found the problem. `setLoop(true)` should work correctly in the next release.

**Comment by jorgegil96** [comment]
Any chance we can get a release with this fix soon?

**Comment by bernardomesk** [comment]
I have to same problem, but I do not want to loop. All I want is the seek bar reset to the beginning and do not play. seekTo(0) not working when called onCompletion callback. Thanks =)
